### ISSUE TITLE
About game rules

### ISSUE THREAD

**Issue by xcx0902** [SZXC-WG/LocalGen-new#12]
In the real generals.io, players can move their armies twice in a turn, but in LocalGen, we can only move once.

**Comment by xcx0902** [comment]
I think it can be easily fixed by doubling the turn number and print the halved turn number.

**Comment by chrhaa** [comment]
This problem can't be decided by you, maybe zly can answer it.

**Comment by AppOfficer** [comment]
The point is, players can only move their armies twice a turn in the custom games in generals.io. So our program's settings is not wrong.

**Comment by AppOfficer** [comment]
We've decided that we will not change the settings in the game. But an update for choosing you favoured text will maybe here in the future.
